### ISSUE TITLE
Error when saving the Settings page..

### ISSUE THREAD

**Issue by tkalfaoglu** [opendocman/opendocman#317]
Almost every time I submit my changes to settings.php, I get this error in the logs and on screen:
[03-Apr-2021 11:26:49 UTC] PHP Fatal error:  Uncaught PDOException: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xC4\xB0\xC5\x9F G...' for column `xxxxopendoc`.`odm_settings`.`value` at row 1 in /var/www/html/opendoc/Settings_class.php:63
Stack trace:
#0 /var/www/html/opendoc/Settings_class.php(63): PDOStatement->execute()
#1 /var/www/html/opendoc/settings.php(65): Settings->save()

Found out that it crashes if the TITLE contains non-ASCII characters..

**Comment by tkalfaoglu** [comment]
Solved: Converted the database and all tables to UTF8
